[package]
name = "wrap-match"
description = "A procedural macro to wrap a function in match statement to make error logging super easy."
authors = ["naturecodevoid"]
homepage = "https://github.com/naturecodevoid/wrap-match"
repository = "https://github.com/naturecodevoid/wrap-match"
documentation = "https://docs.rs/wrap-match"
version = "1.0.3"
edition = "2021"
license = "MIT"

[dependencies]
wrap-match-impl = { version = "=1.0.3", path = "impl" }

[dev-dependencies]
env_logger = "0.10"
futures-executor = "0.3"
log = "0.4"
trybuild = "1.0"

[workspace]
members = ["impl"]
